sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
  - cd generateattcks
install:
  - pip install -U -r requirements.txt
script:
  - python run.py
deploy:
  provider: releases
  file: "generated_attck_data.json"
  skip_cleanup: true